const Main = () => (
    <main className="flex-col h-max px-[40px] mt-[30px]">
        <p className="w-full h-[17px] font-medium text-[14px] text-[#000000]">Technology</p>
        <p className="w-full h-[15px] font-medium text-[12px] text-[#727272]">12 June 2022</p>
        <div className="w-full flex-col box-border px-[20%] gap-[30px] mt-[30px] max-[769px]:px-[10%] max-[500px]:px-[0%]">
            <h2 className="font-semibold text-[40px] justify-center text-center max-[500px]:text-[30px]">China unveils the future of high-speed rail with a next-gen prototype</h2>
            <img src="./public/image/cn-train-1.png" alt="Image1" className="w-full flex justify-center border-[#000000] mt-[30px]" />
            <div className="w-full font-normal text-[16px] text-justify mt-[30px]">
                <p className="mb-[20px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin velit urna, faucibus ac ligula eu, consequat vulputate metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras hendrerit ante vitae erat volutpat, consectetur egestas leo ullamcorper. Phasellus risus mauris, congue vitae ligula quis, gravida viverra leo. Duis feugiat eu felis eu sollicitudin. Pellentesque luctus sit amet diam quis vulputate. Aenean sodales velit sed diam malesuada eleifend. Etiam ac mollis neque. Curabitur id tincidunt velit. Nunc eu massa pulvinar, vestibulum felis porta, bibendum augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                <p className="mb-[20px]">Nullam eu erat eu lorem mollis posuere nec sed tellus. Pellentesque sit amet neque tempor, mollis urna sed, pretium felis. Curabitur nec dapibus nulla, in molestie risus. In efficitur elementum aliquam. Phasellus et viverra felis. Sed convallis, lorem vel sagittis convallis, tellus risus pretium odio, ac convallis erat massa eu nibh. Sed commodo lectus massa, in imperdiet justo semper porttitor. Sed feugiat nisl vehicula, blandit lectus a, tincidunt lorem.</p>
                <p className="mb-[20px]">Duis nec est sit amet est ultrices semper. Aenean eleifend ac ante a laoreet. Donec porta nisl mauris, ut lobortis felis dapibus faucibus. Nullam posuere lacus pellentesque ultricies ultricies. Etiam auctor erat id accumsan finibus. Curabitur sed lectus id neque gravida volutpat. Integer non quam quam. Aenean vel velit eget nisi porttitor viverra. Quisque nec sapien non augue suscipit dignissim. Sed ac ullamcorper justo. Nam varius metus augue, et tincidunt magna imperdiet sit amet. Vestibulum non mi iaculis, fermentum neque nec, luctus risus. Proin vitae posuere ipsum, ut fermentum orci. Nullam laoreet quam quis vulputate laoreet.</p>
                <p className="mb-[20px]">Pellentesque blandit libero imperdiet purus scelerisque efficitur. Curabitur sit amet ante massa. Aenean consectetur vitae urna vitae pharetra. Quisque vulputate tincidunt efficitur. Sed volutpat, sapien quis iaculis pharetra, quam elit pharetra mauris, id imperdiet velit quam elementum nisi. Pellentesque dolor lacus, volutpat ac turpis vel, dictum auctor nisi. Morbi a cursus ex. Etiam nec consectetur erat. Ut vel accumsan felis. Vivamus eu turpis eu quam viverra mollis quis sit amet elit. Fusce id est in felis pulvinar egestas sit amet sed purus. Donec imperdiet pellentesque pulvinar. Vestibulum sagittis nibh sed elit tincidunt placerat. Praesent id gravida nisl. Ut placerat nec urna et pulvinar.</p>
            </div>
            <div className="w-full flex flex-row gap-[4%] mt-[30px] max-[500px]:flex-col">
                <img src="./public/image/cn-train-2.png" alt="Image2" className="w-[48%] max-[500px]:w-full" />
                <img src="./public/image/cn-train-3.png" alt="Image3" className="w-[48%] max-[500px]:w-full max-[500px]:mt-[30px]" />
            </div>
            <div className="w-full font-normal text-[16px] text-justify mt-[30px]">
                <p className="mb-[20px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin velit urna, faucibus ac ligula eu, consequat vulputate metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras hendrerit ante vitae erat volutpat, consectetur egestas leo ullamcorper. Phasellus risus mauris, congue vitae ligula quis, gravida viverra leo. Duis feugiat eu felis eu sollicitudin. Pellentesque luctus sit amet diam quis vulputate. Aenean sodales velit sed diam malesuada eleifend. Etiam ac mollis neque. Curabitur id tincidunt velit. Nunc eu massa pulvinar, vestibulum felis porta, bibendum augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                <p className="mb-[20px]">Nullam eu erat eu lorem mollis posuere nec sed tellus. Pellentesque sit amet neque tempor, mollis urna sed, pretium felis. Curabitur nec dapibus nulla, in molestie risus. In efficitur elementum aliquam. Phasellus et viverra felis. Sed convallis, lorem vel sagittis convallis, tellus risus pretium odio, ac convallis erat massa eu nibh. Sed commodo lectus massa, in imperdiet justo semper porttitor. Sed feugiat nisl vehicula, blandit lectus a, tincidunt lorem.</p>
                <p className="mb-[20px]">Duis nec est sit amet est ultrices semper. Aenean eleifend ac ante a laoreet. Donec porta nisl mauris, ut lobortis felis dapibus faucibus. Nullam posuere lacus pellentesque ultricies ultricies. Etiam auctor erat id accumsan finibus. Curabitur sed lectus id neque gravida volutpat. Integer non quam quam. Aenean vel velit eget nisi porttitor viverra. Quisque nec sapien non augue suscipit dignissim. Sed ac ullamcorper justo. Nam varius metus augue, et tincidunt magna imperdiet sit amet. Vestibulum non mi iaculis, fermentum neque nec, luctus risus. Proin vitae posuere ipsum, ut fermentum orci. Nullam laoreet quam quis vulputate laoreet.</p>
                <p className="mb-[20px]">Pellentesque blandit libero imperdiet purus scelerisque efficitur. Curabitur sit amet ante massa. Aenean consectetur vitae urna vitae pharetra. Quisque vulputate tincidunt efficitur. Sed volutpat, sapien quis iaculis pharetra, quam elit pharetra mauris, id imperdiet velit quam elementum nisi. Pellentesque dolor lacus, volutpat ac turpis vel, dictum auctor nisi. Morbi a cursus ex. Etiam nec consectetur erat. Ut vel accumsan felis. Vivamus eu turpis eu quam viverra mollis quis sit amet elit. Fusce id est in felis pulvinar egestas sit amet sed purus. Donec imperdiet pellentesque pulvinar. Vestibulum sagittis nibh sed elit tincidunt placerat. Praesent id gravida nisl. Ut placerat nec urna et pulvinar.</p>
            </div>
        </div>
    </main>
)

export default Main;